    <header>
        <!-- Logo linking to homepage -->
        <a href="index.html">
            <img src="images/Data_Nexus_Logo-Photoroom.png" id="home-logo" alt="Data Nexus Official Logo">
        </a>

        <!-- Navigation menu to all main pages -->
        <nav id="home-navigation">
            <a href="index.html" class="home-navlinks" id="home-current-page">Home</a>
            <a href="jobs.html" class="home-navlinks">Jobs</a>
            <a href="apply.html" class="home-navlinks">Apply</a>
            <a href="about.html" class="home-navlinks">About</a>
        </nav>
    </header>