    <footer>
        <div class="footer-content">
          <a href="https://student-team-d82481z6.atlassian.net/jira/software/projects/PP1/boards/3/timeline?selectedIssue=PP1-28&atlOrigin=eyJpIjoiOTdlZTc1Mjg2MWIyNDVmYmI0NWRlZDRlZDdhZGNmNWEiLCJwIjoiaiJ9" id="footer-items">Jira Project</a>
          <p>Contact us at <a href="mailto:info@datanexus.com.au">info@datanexus.com.au</a></p>
          <p>&copy; 2024 Data Nexus. All rights reserved.</p>
        </div>
      </footer>