    <header>
        <!-- Logo linking to homepage -->
        <a href="index.php">
            <img src="images/Data_Nexus_Logo-Photoroom.png" id="home-logo" alt="Data Nexus Official Logo">
        </a>

        <!-- Navigation menu to all main pages -->
        <nav id="home-navigation">
            <a href="index.php" class="home-navlinks" id="home-current-page">Home</a>
            <a href="jobs.php" class="home-navlinks">Jobs</a>
            <a href="apply.php" class="home-navlinks">Apply</a>
            <a href="about.php" class="home-navlinks">About</a>
              <a href="login.php" class="home-navlinks">Login</a>
              <a href="managers_register.php" class="home-navlinks">Manager Registration</a>
              <a href="enhancements.php" class="home-navlinks">Enhancements</a>

        </nav>
          
    </header>